name: Deploy to Server

on:
  push:
    branches:
      - master  # Vous pouvez remplacer 'main' par la branche que vous souhaitez suivre.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H lms-app.alwaysdata.net >> ~/.ssh/known_hosts

    - name: Deploy code via SSH
      run: |
        ssh lms-app@lms-app.alwaysdata.net "cd /home/lms-app/www && git pull && ./deploy-script.sh"
