name: Deploy to Server

on:
  push:
    branches:
      - master  # Changez 'main' en 'master' si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p /tmp/.ssh/  # Crée un répertoire temporaire pour SSH
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/.ssh/id_rsa  # Écrit la clé privée
        chmod 600 /tmp/.ssh/id_rsa  # Change les permissions
        ssh-keyscan -H lms-app.alwaysdata.net >> /tmp/.ssh/known_hosts  # Ajoute le serveur aux known_hosts

    - name: Deploy code via SSH
      run: |
        ssh -i /tmp/.ssh/id_rsa lms-app@lms-app.alwaysdata.net "cd /home/lms-app && git pull && ./deploy-script.sh"
