name: Deploy to Server

on:
  push:
    branches:
      - master  # Remplacez par votre branche principale, par exemple 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        # Crée le répertoire ~/.ssh s'il n'existe pas déjà
        mkdir -p ~/.ssh
        # Écrit la clé privée (depuis les Secrets) dans ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        # Définit les permissions appropriées pour la clé privée
        chmod 600 ~/.ssh/id_rsa
        # Ajoute le serveur Alwaysdata à la liste des hôtes connus
        ssh-keyscan -H lms-app.alwaysdata.net >> ~/.ssh/known_hosts

    - name: Deploy code via SSH
      run: |
        # Se connecte au serveur via SSH et exécute les commandes de déploiement
        ssh -i ~/.ssh/id_rsa lms-app@lms-app.alwaysdata.net "cd /home/lms-app && git pull && ./deploy-script.sh"
